### ISSUE TITLE
Use travis CI for testing

### ISSUE THREAD

**Issue by ankitchiplunkar** [analyseether/ether-api#3]
**Is your feature request related to a problem? Please describe.**
We need to use CI tools to validate the library before each pull request and commit.

**Describe the solution you'd like**
Use Travis CI to maintain a minimum 80% code coverage and testing of all API's

**Comment by SaranshVatsa** [comment]
Kindly approve the Travis CI request so that it can be applied to this repository.

**Comment by SaranshVatsa** [comment]
Okay so it shows up on my list of repositories in the personal settings, but not when I try to activate Travis CI on my personal account. So is it because it's already activated on this organization's account and all I have to do is create the .yml file and get started?

**Comment by ankitchiplunkar** [comment]
Yes you need a *.yml file to tell travis about the test deployment details.

**Comment by SaranshVatsa** [comment]
Alright, seems I figured it out finally lol, I shall get to it

**Comment by SaranshVatsa** [comment]
Check the PR, it's done. :)
