### ISSUE TITLE
Can't import the test SQL file you provided in pgAdmin

### ISSUE THREAD

**Issue by SaranshVatsa** [analyseether/ether-api#7]
See the screenshots attached.
It says the execution is complete but no tables show up.

![screenshot 197](https://user-images.githubusercontent.com/28927361/45595488-48295200-b9ca-11e8-930d-c190de636bb6.png)

**Comment by ankitchiplunkar** [comment]
I followed the method given here: https://stackoverflow.com/questions/18736345/export-and-import-table-dump-sql-using-pgadmin

And was able to view the loaded tables.
![image](https://user-images.githubusercontent.com/5904910/45670318-c26cea00-bb22-11e8-9ad9-b7531dd5f66a.png)

**Comment by SaranshVatsa** [comment]
I am getting this error upon following those instructions too.

![screenshot 198](https://user-images.githubusercontent.com/28927361/45689983-eeb05700-bb72-11e8-8826-9a93121686cc.png)


I know it's definitely a problem at my end, maybe with the pgAdmin installation. Anyway, if you could send me just individual SQL files for the main tables that we need to test upon (which I believe would be just blocks, transactions and uncles), then I will try importing them individually and maybe that can work.

**Comment by ankitchiplunkar** [comment]
Added the relevant tables as *.csv through this PR: https://github.com/analyseether/ether-api/pull/9

**Comment by ankitchiplunkar** [comment]
@SaranshVatsa can we close this issue?

**Comment by SaranshVatsa** [comment]
Sure
